version: "3.9"

services:
  blog:
    container_name: blog
    image: denoland/deno:1.36.4
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    command: deno task serve
    ports:
      - 3000:3000
    environment:
      - DENO_DIR=/app/deno-dir
